### ISSUE TITLE
Wrong signature for ATmega168P

### ISSUE THREAD

**Issue by rodgull** [AtmelUniversityFrance/atmel-avr-xmini-boardmanagermodule#7]
I followed all the steps and programmed the fuses and the optiboot bootloader, and  when attempting to load the blink example in arduino 1.6.12 I get the following error:

avrdude: Device signature = 0x1e9406 (probably m168)
avrdude: Expected signature for ATmega168P is 1E 94 0B

Looking through the avrdude.conf file the 1e9406 is listed as m168 and 1e940b is m168p, the chip on the Xplainedmini is the 168PB, so I don't understand what the issue is.  

Querying the board revision in Atmel Studio gives 1e9415, which is different again and doesn't appear anywhere in the avrdude.conf file.

The LED on the board gives two quick flashes then off for a second and then repeats.  I assume this is the bootloader running and resetting as there is no program to run after the bootloader. 

Sorry if this is the wrong way to ask this but I can't find any other relevant information.

**Comment by aethaniel** [comment]
Hi @rodgull, sorry, I receive notifications only if I'm explicitly named into a comment.
So far, your problem seems to be related to avrdude which isn't part of this module.
By the way, this module doesn't handle atmega168P but only atmega168PB.

> The LED on the board gives two quick flashes then off for a second and then repeats.

This is indeed the booloader waiting for sketch programming request coming from Arduino IDE/avrdude through USB/UART.

Did you obtain better results since?
